[project]
authors = ["Maciej Woś"]
entry = "main.sw"
license = "Apache-2.0"
name = "block-indexer"

[dependencies]
ecal_lib = { path = "../../libraries/ecal-lib" }
indexer = { path = "../../libraries/indexer" }